title: Renan Maganha
email: maganha.renan@gmail.com
description: "A blog about programming, vintage game hardware, and other stuff."
baseurl: /
url: "https://maganharenan.github.io"
twitter_username: 
github_username:  maganharenan

# Build settings
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
plugins:
  - jekyll-feed

paginate: 5
paginate_path: "/blog/page:num"